### ISSUE TITLE
Dynamic Navigation Menu for Pages

### ISSUE THREAD

**Issue by mattbischoff** [mattbischoff/matthewbischoff.com#35]
https://jekyllrb.com/tutorials/navigation/

**Comment by Martin-Alexander** [comment]
My understanding:

You want to be able to modify these links without editing the HTML, but rather by editing some config file. Perhaps the config file could look something like this:

```yaml
navigation_links:
- name: "Home"
  url: "/"
- name: "About"
  url: "/about"
- name: "Contact"
  url: "/contact"
- name: "Now"
  url: "/now"
```

![image](https://user-images.githubusercontent.com/19353631/78732227-152e1280-7910-11ea-90cb-e25925fb30f1.png)
